version: "3.2"
services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: ./.env
    ports:
      - 3000:3000
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      SMTP_REPLY_EMAIL: ${SMTP_REPLY_EMAIL}
      SMTP_TLS_CIPHERS: ${SMTP_TLS_CIPHERS}
      SMTP_SECURE: ${SMTP_SECURE}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_SERVER_ID: ${DISCORD_SERVER_ID}
  redis:
    image: redis
    env_file: ./.env
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/redis.conf
    command:
      - redis-server
      - /redis.conf
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 30s
      retries: 3
  postgres:
    image: postgres
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -d
        - outline
        - -U
        - user
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
  https-portal:
    image: steveltn/https-portal
    env_file: ./.env
    ports:
      - 80:80
      - 443:443
    links:
      - outline
    restart: always
    volumes:
      - https-portal-data:/var/lib/https-portal
    healthcheck:
      test:
        - CMD
        - service
        - nginx
        - status
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      DOMAINS: YOUR-DOMAIN-!!!!!!!!!!!!! -> http://outline:3000
      STAGE: production
      WEBSOCKET: "true"
      CLIENT_MAX_BODY_SIZE: "0"
volumes:
  https-portal-data: null
  storage-data: null
  database-data: null
networks: {}
